routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'WelcomeController@index');
Route::get('/posts/{cat_id}', 'WelcomeController@byCategory');
Route::get('/single-post/{id}', 'WelcomeController@singlePost');

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('post', 'PostController');
    Route::resource('courses', 'CourseController');
    Route::resource('courseApproval', 'CourseApprovalController');
    Route::get('courseApprovalList', 'CourseApprovalController@ApprovalList')->name('courseApprovalList.index');
    Route::get('myApprovalcourse', 'CourseApprovalController@myCourse')->name('myApprovalcourse');
    Route::match(['get', 'post'], 'coursesApprove/{course}', 'CourseApprovalController@ApproveMe')->name('courseApprove.approveMe');
    Route::match(['get', 'post'], 'ApproveMyCourse/{course}', 'CourseApprovalController@ApproveMyCourse')->name('courseApprove.approveMyCourse');
    Route::get('trashed_posts', 'PostController@trashed')->name('trashed_posts.index');
    Route::put('restore_posts/{post}', 'PostController@restore')->name('restore_posts');
    Route::match(['get', 'post'], 'allposts', 'PostController@AllPost')->name('posts.allPost');
    Route::resource('post/{post}/replies', 'ReplaiesController');
    Route::resource('/poll', 'PollController');
    Route::resource('/pollanswer', 'PollAnswerController');
    Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-teacher', 'UsersController@makeTeacher')->name('users.make-teacher');

});

app/Category.php
<?php

namespace App;
use App\Course;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
     protected $fillable = ['name','course_id','user_id'];

     public function post()
     {
     	return $this->hasMany(Post::class);
     }
     public function course()
    {
        return $this->belongsTo(Course::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\Course;
use App\courseApproval;
use Gate;
use Illuminate\Http\Request;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use Illuminate\Support\Facades\Auth;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::latest('created_at')->get();
        return view('category.index')->with('categories', $category)->with('posts', Post::all())->with('courseApprovals', courseApproval::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }
        }
        $courses = Course::where('user_id', Auth::user()->id)->get();
        return view('category.create')->with('courses', $courses);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {

        //dd($request->all());
        Category::create([
            'name' => $request->name,
            'course_id' => $request->course,
            'user_id' => auth()->user()->id

        ]);
        session()->flash('success', 'Category created successfully.');
        return redirect(route('categories.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //dd($category);
        return view('category.post_list')->with('categories', $category)->with('posts', Post::all());
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }
        }
        return view('category.create')->with('category', $category)->with('courses', Course::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update([
            'name' => $request->name,
            'course_id' => $request->course
        ]);
        //session()->flash('success', 'Category updated successfully.');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }

        }
        if ($category->post->count() > 0) {
            session()->flash('danger', 'Category cannot be deleted because it has some posts.');

            return redirect()->back();
        }
        $category->delete();

        session()->flash('denger', 'Category deleted successfully.');

        return redirect(route('categories.index'));
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Create Category</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3"></div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-default">
                        <div class="card-body">
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul class="list-group">
                                        @foreach($errors->all() as $error)
                                            <li class="list-group-item">
                                                {{ $error }}
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }}"
                                  method="POST">
                                {{ csrf_field() }}
                                @if(isset($category))
                                    {{ method_field('PUT') }}
                                @endif
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" id="name" class="form-control" name="name"
                                           value="{{ isset($category) ? $category->name : '' }}">
                                </div>
                                <div class="form-group">
                                    <label for="course">Course</label>
                                    <select name="course" id="course" class="form-control">
                                        @foreach($courses as $course)
                                            <option value="{{ $course->id }}"
                                                    @if(isset($category))
                                                    @if($course->id === $category->course_id)
                                                    selected
                                                    @endif
                                                    @endif
                                            >
                                                {{ $course->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group text-center">

                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Category</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            @if(auth()->user()->isAdmin() || auth()->user()->isTeacher() )
                                <div><a class="btn btn-primary" href="{{ route('categories.create') }}">Add category</a>
                                </div>
                            @endif

                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Course</th>
                                    <th>Posts Count</th>
                                    <th></th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($courseApprovals as $courseApproval)
                                    @if(Auth::id()===$courseApproval->user_id )
                                        @foreach($categories as $category)
                                            @if($category->course_id === $courseApproval->course_id)
                                                <tr>

                                                    <td>
                                                        <a href="{{ route('categories.show', $category->id) }}"> {{ $category->name }}</a>
                                                    </td>
                                                    <td>
                                                        {{$category->course->name}}
                                                    </td>
                                                    <td>
                                                        {{ $category->post->count() }}
                                                    </td>
                                                    @if(auth()->user()->isAdmin() || Auth::id() === $category->user_id )
                                                        <td>
                                                            <a href="{{ route('categories.edit', $category->id) }}"
                                                               class="btn btn-info btn-sm">
                                                                Edit
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <form method="POST"
                                                                  action="{{ route('categories.destroy', $category->id) }}">
                                                                {{ csrf_field() }}
                                                                {{ method_field('DELETE') }}
                                                                <button type="submit" class="btn btn-danger btn-sm">
                                                                    Delete
                                                                </button>
                                                            </form>
                                                        </td>
                                                    @endif
                                                </tr>
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/category/post_list.blade.php
@extends('layouts.app')

@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Post for {{ $categories->name }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Post</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">


                                @foreach($posts as $post)

                                    @if($post->category->id === $categories->id)
                                        <tr>

                                            <td>
                                                <h4><a href="{{ route('post.show', $post->id) }}" > {{ $post->title }}</a></h4>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection