routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'WelcomeController@index');
Route::get('/posts/{cat_id}', 'WelcomeController@byCategory');
Route::get('/single-post/{id}', 'WelcomeController@singlePost');

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('post', 'PostController');
    Route::resource('courses', 'CourseController');
    Route::resource('courseApproval', 'CourseApprovalController');
    Route::get('courseApprovalList', 'CourseApprovalController@ApprovalList')->name('courseApprovalList.index');
    Route::get('myApprovalcourse', 'CourseApprovalController@myCourse')->name('myApprovalcourse');
    Route::match(['get', 'post'], 'coursesApprove/{course}', 'CourseApprovalController@ApproveMe')->name('courseApprove.approveMe');
    Route::match(['get', 'post'], 'ApproveMyCourse/{course}', 'CourseApprovalController@ApproveMyCourse')->name('courseApprove.approveMyCourse');
    Route::get('trashed_posts', 'PostController@trashed')->name('trashed_posts.index');
    Route::put('restore_posts/{post}', 'PostController@restore')->name('restore_posts');
    Route::match(['get', 'post'], 'allposts', 'PostController@AllPost')->name('posts.allPost');
    Route::resource('post/{post}/replies', 'ReplaiesController');
    Route::resource('/poll', 'PollController');
    Route::resource('/pollanswer', 'PollAnswerController');
    Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-teacher', 'UsersController@makeTeacher')->name('users.make-teacher');

});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function posts()
    {
      return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tag=Tag::latest('created_at')->get();
        return view('tag.index')->with('tags',$tag);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
         Tag::create([
          'name' => $request->name

        ]);
         session()->flash('success', 'Tag created successfully.');
         return redirect(route('tags.index'));
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tag.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $Tag)
    {
        $Tag->update([
          'name' => $request->name
        ]);
    //session()->flash('success', 'Tag updated successfully.');
        return redirect(route('tag.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $Tag)
    {
        if ($tag->posts->count() > 0) {
          session()->flash('error', 'Tag cannot be deleted, because it is associated to some posts.');

          return redirect()->back();
        }
        $Tag->delete();

        session()->flash('denger', 'Tag deleted successfully.');

        return redirect(route('tag.index'));
    }
}

resources/views/tag/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Tag</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Create Tag</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3"></div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            @include('partials.errors')
                            <form action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}"
                                  method="POST">
                                {{ csrf_field() }}
                                @if(isset($tag))
                                    {{ method_field('PUT') }}
                                @endif
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" id="name" class="form-control" name="name"
                                           value="{{ isset($tag) ? $tag->name : '' }}">
                                </div>
                                <div class="form-group text-center">

                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Tag</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Tag</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <div><a class="btn btn-primary" href="{{ route('tags.create') }}">Add Tag</a></div>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Posts Count</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($tags as $tag)
                                    <tr>
                                        <td>
                                            {{ $tag->name }}
                                        </td>
                                        <td>
                                            {{ $tag->posts->count() }}
                                        </td>
                                        <td>
                                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info btn-sm">
                                                Edit
                                            </a></td>
                                        <td>
                                            <form method="POST" action="{{ route('tags.destroy', $tag->id) }}">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection