routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'WelcomeController@index');
Route::get('/posts/{cat_id}', 'WelcomeController@byCategory');
Route::get('/single-post/{id}', 'WelcomeController@singlePost');

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('post', 'PostController');
    Route::resource('courses', 'CourseController');
    Route::resource('courseApproval', 'CourseApprovalController');
    Route::get('courseApprovalList', 'CourseApprovalController@ApprovalList')->name('courseApprovalList.index');
    Route::get('myApprovalcourse', 'CourseApprovalController@myCourse')->name('myApprovalcourse');
    Route::match(['get', 'post'], 'coursesApprove/{course}', 'CourseApprovalController@ApproveMe')->name('courseApprove.approveMe');
    Route::match(['get', 'post'], 'ApproveMyCourse/{course}', 'CourseApprovalController@ApproveMyCourse')->name('courseApprove.approveMyCourse');
    Route::get('trashed_posts', 'PostController@trashed')->name('trashed_posts.index');
    Route::put('restore_posts/{post}', 'PostController@restore')->name('restore_posts');
    Route::match(['get', 'post'], 'allposts', 'PostController@AllPost')->name('posts.allPost');
    Route::resource('post/{post}/replies', 'ReplaiesController');
    Route::resource('/poll', 'PollController');
    Route::resource('/pollanswer', 'PollAnswerController');
    Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-teacher', 'UsersController@makeTeacher')->name('users.make-teacher');

});

app/Course.php
<?php

namespace App;
use App\Category;
use App\courseApproval;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    protected $fillable = [
      'name', 'description','schedule','user_id'
    ];
    public function category()
     {
     	return $this->hasMany(Category::class);
     }
     public function courseapproval()
     {
     	return $this->hasMany(courseApproval::class);
     }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Category;
use App\courseApproval;
use Gate;
use Illuminate\Http\Request;
use App\Http\Requests\course\CreateCourseRequest;
use App\Http\Requests\course\UpdateCourseRequest;

class CourseController extends Controller
{
    //public $approval_id;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courseApprovals = courseApproval::all();
        if (count($courseApprovals) < 1) {
            $courseApprovals = [];
        }
        $courses = Course::latest('created_at')->get();
        //return view('course.index')->with('courses', $course)->with('courseApprovals', $courseApprovals);
        return view('course.index', compact('courses', 'courseApprovals'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }

        }
        return view('course.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCourseRequest $request)
    {
        Course::create([
            'name' => $request->name,
            'description' => $request->description,
            'schedule' => $request->schedule,
            'user_id' => auth()->user()->id

        ]);
        session()->flash('success', 'course created successfully.');
        return redirect(route('courses.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Course $course)
    {
        //dd($course->all());
        return view('course.category_list')->with('courses', $course)->with('categories', Category::all());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course)
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }

        }
        return view('course.create')->with('course', $course);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCourseRequest $request, Course $course)
    {
        $course->update([
            'name' => $request->name,
            'description' => $request->description,
            'schedule' => $request->schedule
        ]);
        //session()->flash('success', 'Category updated successfully.');
        return redirect('/courses');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Course $course)
    {
        if (!Gate::allows('is_admin')) {
            if (!Gate::allows('is_teacher')) {
                abort(404, "You can not access this page");
            }
        }
        if ($course->category->count() > 0) {
            session()->flash('danger', 'Category cannot be deleted because it has some posts.');

            return redirect()->back();
        }

        $course->delete();

        session()->flash('danger', 'Course deleted successfully.');

        return redirect()->back();
    }

}

resources/views/course/category_list.blade.php
@extends('layouts.app')


@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Categories for {{ $courses->name }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Categories</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">
                                @foreach($categories as $category)

                                    @if($category->course_id === $courses->id)
                                        <tr>

                                            <td>
                                                <a href="{{ route('categories.show', $category->id) }}">{{ $category->name }}</a>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/course/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create course</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Create course</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3"></div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-default">
                        <div class="card-body">
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul class="list-group">
                                        @foreach($errors->all() as $error)
                                            <li class="list-group-item">
                                                {{ $error }}
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ isset($course) ? route('courses.update', $course->id) : route('courses.store') }}"
                                  method="POST">
                                {{ csrf_field() }}
                                @if(isset($course))
                                    {{--{{ method_field('PUT') }}--}}
                                    <input type="hidden" name="_method" value="PUT">
                                @endif
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" id="name" class="form-control" name="name"
                                           value="{{ isset($course) ? $course->name : '' }}">
                                </div>
                                <div class="form-group">
                                    <label for="name">Description</label>
                                    <input type="text" id="name" class="form-control" name="description"
                                           value="{{ isset($course) ? $course->description : '' }}">
                                </div>
                                <div class="form-group">
                                    <label for="name">Schedule</label>
                                    <input type="text" id="name" class="form-control" name="schedule"
                                           value="{{ isset($course) ? $course->schedule : '' }}">
                                </div>


                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/course/create_poll.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Poll</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Create Poll</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-3"></div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-default">
                        <div class="card-body">
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul class="list-group">
                                        @foreach($errors->all() as $error)
                                            <li class="list-group-item">
                                                {{ $error }}
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ action('PollController@store') }}"
                                  method="POST">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="name">Course</label>
                                    <select class="form-control" name="course_id" required>
                                        <option value="">--Select Course--</option>
                                        @foreach($courses as $course)
                                            <option value="{{ $course->id }}">{{ $course->name }}</option>
                                        @endforeach        
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="name">Question</label>
                                    <input type="text" name="question" class="form-control" required>
                                </div>
                                
                                <div class="form-group">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <td>Action</td>
                                            <td>Option</td>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>
                                                <button type="button" onclick="addRow()" class="btn btn-primary">+
                                                </button>
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" name="options[]" id="option_1" value="">
                                                <input type="hidden" name="row" id="row" class="row" value="1">
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>

                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        function addRow() {
            var row = parseInt($('#row').val());
            row = row + 1;
            var str = '<tr id="tr_' + row + '">';
            str += '<td><button type="button" onclick="removeRow(' + row + ')" class="btn btn-danger">-</button></td>';
            str += '<td><input type="text" class="form-control" name="options[]" id="option_' + row + '" value=""</td>';
            str += '</tr>';
            $('table>tbody').append(str);
            $('#row').val(row);
            $('.select2').select2();
        }

        function removeRow(row) {
            $('#tr_' + row).remove();
            var current = Number($('#row').val());
            var row = current - 1;
            $('#row').val(row);
            calculateTotalPrice();
        }
    </script>

@endsection

resources/views/course/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All course</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All course</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            @if(auth()->user()->isAdmin() || auth()->user()->isTeacher() )
                                <div><a class="btn btn-primary" href="{{ route('courses.create') }}">Add course</a>
                                </div>
                            @endif
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th></th>
                                </tr>
                                </thead>

                                <tbody>


                                @foreach($courses as $course)
                                    <tr>
                                        <?php $flag = 0; ?>

                                        @if(auth()->user()->isAdmin() || Auth::id() === $course->user_id )
                                            <td>
                                                <a href="{{ route('courses.show', $course->id) }}"> {{ $course->name }}</a>
                                            </td>
                                            <td>
                                                <a href="{{ route('courses.edit', $course->id) }}"
                                                   class="btn btn-info btn-sm">
                                                    Edit
                                                </a></td>
                                            <td>
                                                <form method="POST"
                                                      action="{{ route('courses.destroy', $course->id) }}">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                </form>
                                            </td>
                                            <?php
                                            $courseApproval = (object)array('id' => 0);
                                            ?>
                                            @foreach($courseApprovals as $courseApproval)
                                                @if($courseApproval->course_id ===  $course->id && Auth::id() ===$courseApproval->user_id)
                                                    <?php
                                                    $flag = 1; ?>
                                                @endif
                                            @endforeach
                                            @if($flag=== 0)

                                                <td>
                                                    <form method="POST"
                                                          action="{{ route('courseApprove.approveMyCourse',$courseApproval->id) }}">
                                                        {{ csrf_field() }}
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="courseId"
                                                                   value="{{ $course->id }}">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="ApproveId"
                                                                   value="{{ Auth::id() }}">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="courseUserId"
                                                                   value="{{ $course->user_id}}">
                                                        </div>
                                                        <button type="submit" class="btn btn-success btn-sm">Add me
                                                        </button>
                                                    </form>
                                                </td>

                                            @endif
                                            {{--@endforeach--}}
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection


resources/views/course/polls.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Polls</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All polls</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Course Name</th>
                                    <th>Answer</th>
                                    <th>Total Votes</th>
                                </tr>
                                </thead>

                                <tbody>

                                @foreach($polls as $poll)
                                    <?php
                                    $course = \Illuminate\Support\Facades\DB::table('courses')->where('id', $poll->course_id)->first();
                                    ?>
                                    <tr>
                                        <td>
                                            <a href="{{ route('courses.show', $course->id) }}"> {{ $course->name }}</a>
                                        </td>
                                        <td>
                                            {{ $poll->answer }}
                                        </td>
                                        <td>
                                            {{ $poll->total_answer }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
