routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'WelcomeController@index');
Route::get('/posts/{cat_id}', 'WelcomeController@byCategory');
Route::get('/single-post/{id}', 'WelcomeController@singlePost');

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('tags', 'TagsController');
    Route::resource('post', 'PostController');
    Route::resource('courses', 'CourseController');
    Route::resource('courseApproval', 'CourseApprovalController');
    Route::get('courseApprovalList', 'CourseApprovalController@ApprovalList')->name('courseApprovalList.index');
    Route::get('myApprovalcourse', 'CourseApprovalController@myCourse')->name('myApprovalcourse');
    Route::match(['get', 'post'], 'coursesApprove/{course}', 'CourseApprovalController@ApproveMe')->name('courseApprove.approveMe');
    Route::match(['get', 'post'], 'ApproveMyCourse/{course}', 'CourseApprovalController@ApproveMyCourse')->name('courseApprove.approveMyCourse');
    Route::get('trashed_posts', 'PostController@trashed')->name('trashed_posts.index');
    Route::put('restore_posts/{post}', 'PostController@restore')->name('restore_posts');
    Route::match(['get', 'post'], 'allposts', 'PostController@AllPost')->name('posts.allPost');
    Route::resource('post/{post}/replies', 'ReplaiesController');
    Route::resource('/poll', 'PollController');
    Route::resource('/pollanswer', 'PollAnswerController');
    Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');
});
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-teacher', 'UsersController@makeTeacher')->name('users.make-teacher');

});

resources/views/Approval/candidate_list.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All candidate</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All candidate</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            @if(auth()->user()->isAdmin() || auth()->user()->isTeacher() )
                                <div><a class="btn btn-primary" href="{{ route('categories.create') }}">Add category</a>
                                </div>
                            @endif

                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Posts Count</th>
                                    <th></th>
                                </tr>

                                </thead>

                                <tbody>
                                @foreach($categories as $category)
                                    <tr>

                                        <td>
                                            <a href="{{ route('categories.show', $category->id) }}"> {{ $category->name }}</a>
                                        </td>

                                        <td>
                                            {{ $category->post->count() }}
                                        </td>
                                        @if(auth()->user()->isAdmin() || Auth::id() === $category->user_id )
                                            <td>
                                                <a href="{{ route('categories.edit', $category->id) }}"
                                                   class="btn btn-info btn-sm">
                                                    Edit
                                                </a>
                                            </td>
                                            <td>
                                                <form method="POST"
                                                      action="{{ route('categories.destroy', $category->id) }}">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                </form>
                                            </td>
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/Approval/courseApprovalRequest.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Course Approval Request</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Course Approval List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Course Name</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($courseApprovals as $courseApproval)
                                    @if($courseApproval->course)
                                        @if(Auth::id()===$courseApproval->course_user_id)
                                            <tr>
                                                <td>
                                                    {{ $courseApproval->user->name }}
                                                </td>
                                                <td>
                                                    {{ $courseApproval->course->name }}
                                                </td>
                                                <td>
                                                    @if($courseApproval->status === 0)

                                                        <form action="{{ route('courseApproval.update',$courseApproval->id) }}"
                                                              method="POST">
                                                            {{ csrf_field() }}
                                                            @if(isset($courseApproval))
                                                                {{ method_field('PUT') }}
                                                            @endif

                                                            <button type="submit" class="btn btn-success btn-sm">Accept
                                                            </button>
                                                        </form>
                                                    @else
                                                        <form method="POST"
                                                              action="{{ route('courseApproval.destroy', $courseApproval->id) }}">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="submit" class="btn btn-danger btn-sm">Delete
                                                            </button>
                                                        </form>

                                                    @endif
                                                </td>
                                            </tr>

                                        @endif
                                    @endif
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Approval/courseRequest.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Course request</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Course request</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <?php
                                $Approve_id = Auth::id();
                                ?>
                                <tbody>

                                @foreach($courses as $course)
                                    <tr>
                                        <td>
                                            {{ $course->name }}
                                        </td>
                                        <?php
                                        $flag = 0;
                                        $flag1 = 0;
                                        ?>

                                        @if(Auth::id()!== $course->user_id)
                                            @foreach($courseApprovals as $courseApproval)


                                                @if($courseApproval->course_id === $course->id && Auth::id()=== $courseApproval->user_id && $courseApproval->status === 0)

                                                    <td>
                                                        <form method="POST"
                                                              action="{{ route('courseApproval.destroy', $courseApproval->id) }}">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="submit" class="btn btn-danger btn-sm">Cencel
                                                                Request
                                                            </button>
                                                        </form>
                                                        <?php
                                                        $flag = 1;
                                                        break;
                                                        ?>
                                                    </td>
                                                @endif
                                                @if($courseApproval->course_id === $course->id && Auth::id()=== $courseApproval->user_id && $courseApproval->status === 1)

                                                    <td>
                                                        <form method="POST"
                                                              action="{{ route('courseApproval.destroy', $courseApproval->id) }}">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button type="submit" class="btn btn-danger btn-sm">Exit
                                                            </button>
                                                        </form>
                                                        <?php
                                                        $flag1 = 1;
                                                        break;
                                                        ?>
                                                    </td>
                                                @endif

                                            @endforeach
                                            @if($flag!==1 && $flag1!==1 )
                                                <td>
                                                    <form method="POST"
                                                          action="{{ route('courseApprove.approveMe',$course->id) }}">
                                                        {{ csrf_field() }}
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="courseId"
                                                                   value="{{ $course->id }}">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="ApproveId"
                                                                   value="{{ $Approve_id }}">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="hidden" id="name" class="form-control"
                                                                   name="courseUserId"
                                                                   value="{{ $course->user_id}}">
                                                        </div>
                                                        <button type="submit" class="btn btn-success btn-sm">Add me
                                                        </button>
                                                    </form>

                                                    <?php
                                                    $flag = 0;
                                                    $flag1 = 0;
                                                    ?>
                                                    @endif
                                                    @endif
                                                </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Approval/myApprovalCourse.blade.php
@extends('layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">My courses</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">My courses</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="content-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card card-default">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>

                                    <th></th>
                                </tr>
                                </thead>

                                <tbody>


                                @foreach($courseApprovals as $courseApproval)
                                    <tr>
                                        @if($courseApproval->course)
                                            @if(auth()->user()->isAdmin() || Auth::id() === $courseApproval->user_id )
                                                <td>
                                                    <a href="{{ route('courses.show', $courseApproval->course_id) }}"> {{ $courseApproval->course->name }}</a>
                                                </td>

                                            @endif
                                        @endif
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection